// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Option defines model for Option.
type Option struct {
	// Id Stable option ID (hard-coded server-side).
	Id string `json:"id"`

	// Label Text shown to voters.
	Label string `json:"label"`
}

// Poll defines model for Poll.
type Poll struct {
	Description *string `json:"description,omitempty"`

	// Id Identifier of the poll (single active poll in this app).
	Id      string   `json:"id"`
	Options []Option `json:"options"`
	Title   string   `json:"title"`
}

// Results defines model for Results.
type Results struct {
	Options []struct {
		Id    string `json:"id"`
		Label string `json:"label"`
		Votes int    `json:"votes"`
	} `json:"options"`
	PollId     string `json:"pollId"`
	TotalVotes int    `json:"totalVotes"`
}

// Vote defines model for Vote.
type Vote struct {
	// ChoiceId Must match one of the poll's option IDs.
	ChoiceId string `json:"choiceId"`
	PollId   string `json:"pollId"`

	// VotedAt Server timestamp when this vote was last recorded.
	VotedAt time.Time `json:"votedAt"`
}

// PostVoteJSONBody defines parameters for PostVote.
type PostVoteJSONBody struct {
	// ChoiceId ID of an available option.
	ChoiceId string `json:"choiceId"`
}

// PostVoteJSONRequestBody defines body for PostVote for application/json ContentType.
type PostVoteJSONRequestBody PostVoteJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get poll metadata and options
	// (GET /poll)
	GetPoll(c *gin.Context)
	// Get aggregate results
	// (GET /results)
	GetResults(c *gin.Context)
	// Get my current vote
	// (GET /vote)
	GetVote(c *gin.Context)
	// Cast or change my vote (upsert)
	// (POST /vote)
	PostVote(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetPoll operation middleware
func (siw *ServerInterfaceWrapper) GetPoll(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPoll(c)
}

// GetResults operation middleware
func (siw *ServerInterfaceWrapper) GetResults(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetResults(c)
}

// GetVote operation middleware
func (siw *ServerInterfaceWrapper) GetVote(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetVote(c)
}

// PostVote operation middleware
func (siw *ServerInterfaceWrapper) PostVote(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostVote(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/poll", wrapper.GetPoll)
	router.GET(options.BaseURL+"/results", wrapper.GetResults)
	router.GET(options.BaseURL+"/vote", wrapper.GetVote)
	router.POST(options.BaseURL+"/vote", wrapper.PostVote)
}

type GetPollRequestObject struct {
}

type GetPollResponseObject interface {
	VisitGetPollResponse(w http.ResponseWriter) error
}

type GetPoll200ResponseHeaders struct {
	SetCookie string
}

type GetPoll200JSONResponse struct {
	Body    Poll
	Headers GetPoll200ResponseHeaders
}

func (response GetPoll200JSONResponse) VisitGetPollResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetResultsRequestObject struct {
}

type GetResultsResponseObject interface {
	VisitGetResultsResponse(w http.ResponseWriter) error
}

type GetResults200JSONResponse Results

func (response GetResults200JSONResponse) VisitGetResultsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetVoteRequestObject struct {
}

type GetVoteResponseObject interface {
	VisitGetVoteResponse(w http.ResponseWriter) error
}

type GetVote200ResponseHeaders struct {
	SetCookie string
}

type GetVote200JSONResponse struct {
	Body    Vote
	Headers GetVote200ResponseHeaders
}

func (response GetVote200JSONResponse) VisitGetVoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetVote204ResponseHeaders struct {
	SetCookie string
}

type GetVote204Response struct {
	Headers GetVote204ResponseHeaders
}

func (response GetVote204Response) VisitGetVoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(204)
	return nil
}

type PostVoteRequestObject struct {
	Body *PostVoteJSONRequestBody
}

type PostVoteResponseObject interface {
	VisitPostVoteResponse(w http.ResponseWriter) error
}

type PostVote200ResponseHeaders struct {
	SetCookie string
}

type PostVote200JSONResponse struct {
	Body    Vote
	Headers PostVote200ResponseHeaders
}

func (response PostVote200JSONResponse) VisitPostVoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostVote400JSONResponse Error

func (response PostVote400JSONResponse) VisitPostVoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostVote429JSONResponse Error

func (response PostVote429JSONResponse) VisitPostVoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get poll metadata and options
	// (GET /poll)
	GetPoll(ctx context.Context, request GetPollRequestObject) (GetPollResponseObject, error)
	// Get aggregate results
	// (GET /results)
	GetResults(ctx context.Context, request GetResultsRequestObject) (GetResultsResponseObject, error)
	// Get my current vote
	// (GET /vote)
	GetVote(ctx context.Context, request GetVoteRequestObject) (GetVoteResponseObject, error)
	// Cast or change my vote (upsert)
	// (POST /vote)
	PostVote(ctx context.Context, request PostVoteRequestObject) (PostVoteResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetPoll operation middleware
func (sh *strictHandler) GetPoll(ctx *gin.Context) {
	var request GetPollRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPoll(ctx, request.(GetPollRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPoll")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetPollResponseObject); ok {
		if err := validResponse.VisitGetPollResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetResults operation middleware
func (sh *strictHandler) GetResults(ctx *gin.Context) {
	var request GetResultsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetResults(ctx, request.(GetResultsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetResults")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetResultsResponseObject); ok {
		if err := validResponse.VisitGetResultsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVote operation middleware
func (sh *strictHandler) GetVote(ctx *gin.Context) {
	var request GetVoteRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetVote(ctx, request.(GetVoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVote")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetVoteResponseObject); ok {
		if err := validResponse.VisitGetVoteResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostVote operation middleware
func (sh *strictHandler) PostVote(ctx *gin.Context) {
	var request PostVoteRequestObject

	var body PostVoteJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PostVote(ctx, request.(PostVoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostVote")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PostVoteResponseObject); ok {
		if err := validResponse.VisitPostVoteResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RYf2/bNhD9KgduQBNAdmw3A1rvj6FNh8EY1nhNsGFri/Ysni02FKmSlBOtyHcfSMqS",
	"HCs/3Kb/JDJ9JO/evXt38heW6rzQipSzbPqF2TSjHMPjr8Zo4x+Qc+GEVijnRhdknCDLpkuUlhJWdJb8",
	"YZz8f1cVxKbMOiPUil0nLCdrcdX33XXCDH0uhSHOpm/jCa39+2RjrxefKHX+rNPCe7OnZ4L7v5xsakS9",
	"n505XEgCHT7D7BUcZGj4wLvAwZJZkxlYwelwyJLdkCQuSO4eek5XDmymLxU4DWvtyNie/TfCFpxtTuwL",
	"ea6l3DPgLa96MtIHyIyTcmIpyIBegssICi0lHFihVpIAUyfW9ZpQ4DJhAYuiH56IasTeUR4efjS0ZFP2",
	"w1FLuqOacUd1Vj1XhJrFHePmXDQGK/+lE04+gEYBz2jbutKH7BuypYzc3wPcvuD2JuPtjNr5xtMo7MyF",
	"EnmZs+moiUUoRysyd1Fqc0AfADcB9tmd9fvntEP511e4Up+5dcLdafE2+2pPpkVKsx5a/1FaBzm6NAOt",
	"qEvtJ7atfttL4zvg8JjyF65HV4J0gBM5WYd5AZcZ1eXi98AlWpBoHRhKteHE/c1LbXJ0bMo4Ohr4vfeK",
	"RgNrE3rr1C6ofrdQS92Dj88kSsj0YlF5F4VawYv5DJbaAHrMgj8BseE7NYA6QEvOAoLUajWQYk0cPga9",
	"+yD4R0i1vhAEWsFSmBDr55KsC/tPFUUkCjJRIn+G+enZORyFVS8rCsrCkqntI1MADUFHooMGESwwvSDF",
	"h+9UU/NT9lIYl3GswEunD8ZjQ8bGiMfD0XAUVYoUFoJN2dOwlLACXRb4dFTUoruinhy/IVcaZVuRDBcn",
	"0LFKABUHXKOQnT5jh7eF0+k4w1AeZNAbevqx38iFJuAZYAutbCT9ZDSKfVc5UsFNLAop0rDx6JON4k9X",
	"mBdy0xeWWMpgukZZ0m5oc5FexEIJK0P4R5eQooI0Q7UiqHRpIBeKg0RHxvvqBY0tOFaDyWjyU6e2p2+j",
	"2rELNKgvqJGkKfu9XrlOahOOKu0avPKfB6fLZWvyuRT/dSzm5QL+9EvX79vM/51haMCl5HBJUEisQNGV",
	"+yWWQOw393WjgHWwv4GNT7VP6ybAhGWEnEzA9ozc4CTwvqfIsPIF0y0REYUolYKUA67JgtIOMlxTwL8i",
	"58FtPb4pBzGgMs/RVJEjkYs5OeTocMtTb3tk2nZ3N629UIfStKFIN1R4rf3HQYgBODkUMvKYrgpto5Lt",
	"EHfTY78Ld/dgWtNHx6MHkK61fn4v/1rbp56Km6axVRLd7nk82YOLG/h66PhitTK0QkeQ6lK5mORtQmBj",
	"YppzEhaE9kHilqKUZJ5YSEtjPE+DRB+IzajIYVHt6v5h4tmNquolROju34UN7RCwyVVvLprWzfzCYPRs",
	"8HR8Pn42nUym4/G/+whFCKUnMyddtJa6VPxbpSIX1s/hcKDia4WXh8P79CFhk9Hx7g2v2yNCk29mE/NI",
	"Xu6tW3m1RbA4etkebp4YQq9K2kBZ8PC4RdMacBNX6yM9CRK4oOoWug7fqdmycw5kaAGlIeRhICKeRIwM",
	"FRLTeKcwUBhaC11aiLyLI8g23efatnwPI9BLzavHpXoUsRusfZTRefbKj8uodsaY+19pm0P7R9HW1JmS",
	"rr9KDb6tRP16M4LDQRqIxVti8cOHF8OZH4W3K0G4MOg/sCASdry3AAq1Rin4SQB6mxvhd5iNwYeYis7P",
	"KtMmO37Y9kMHQjCts7uPAsbfiXrwncXbobnqwF/UeQPrzL51Fz/0dX88ef5oub/VuXOtIUdVATpHeeEs",
	"HFjhkYXZHFxmtHOSDm/00xP/0qbNZhDOq7oZxleVw5DI/wMAAP//v9QEiFITAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
